export const data = [
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  ,
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
];
