export const data = [
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  ,
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
];


export const companyData = [
  {
    src: '/img/cc1.jpg',
    name: '주식회사 셀프메이드',
    desc: '더 편한 생활용품을 만드는 <주식회사 셀프메이드> 입니다.',
    category: '식품/리빙',
    numofproject: '3개의 프로젝트',
    heartsrc: '/img/emptyhart.jpg',
  },
  {
    src: '/img/cc2.jpg',
    name: '농업회사법인 주식회사 벗드림',
    desc: '부산에서 생산되는 농산물을 이용하여 전통주를 만드는 회사입니다.',
    category: '식품/리빙',
    numofproject: '3개의 프로젝트',
    heartsrc: '/img/emptyhart.jpg',
  },
  {
    src: '/img/cc3.jpg',
    name: '(주)마링',
    desc: '(주)마링, 안고 자는 감정 일기,마봉이입니다.',
    category: '공예',
    numofproject: '1개의 프로젝트',
    heartsrc: '/img/emptyhart.jpg',
  },
  {
    src: '/img/cc4.jpg',
    name: '(주)스퀴즈브루어리',
    desc: '양조장비의 차이가 맥주 품질의 차이를 만듭니다.',
    category: '식품/리빙',
    numofproject: '3개의 프로젝트',
    heartsrc: '/img/emptyhart.jpg',
  },
];