export const BASE_URL = 'http://127.0.0.1:8000';
export const data = [
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  ,
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
  {
    src: '/img/card1.jpg',
    title: '끈적임 없는 참마크림, 비건크림',
    category: '뷰티',
    username: '강민정',
    numofPeople: 34,
    days: 24,
    price: '50,000',
    totalprice: '560,000',
  },
];

export const companyData = [
  {
    src: '/img/cc1.jpg',
    name: '주식회사 셀프메이드',
    desc: '더 편한 생활용품을 만드는 <주식회사 셀프메이드> 입니다.',
    category: '식품/리빙',
    numofproject: '3개의 프로젝트',
    heartsrc: '/img/emptyhart.jpg',
  },
  {
    src: '/img/cc2.jpg',
    name: '농업회사법인 주식회사 벗드림',
    desc: '부산에서 생산되는 농산물을 이용하여 전통주를 만드는 회사입니다.',
    category: '식품/리빙',
    numofproject: '3개의 프로젝트',
    heartsrc: '/img/emptyhart.jpg',
  },
  {
    src: '/img/cc3.jpg',
    name: '(주)마링',
    desc: '(주)마링, 안고 자는 감정 일기,마봉이입니다.',
    category: '공예',
    numofproject: '1개의 프로젝트',
    heartsrc: '/img/emptyhart.jpg',
  },
  {
    src: '/img/cc4.jpg',
    name: '(주)스퀴즈브루어리',
    desc: '양조장비의 차이가 맥주 품질의 차이를 만듭니다.',
    category: '식품/리빙',
    numofproject: '3개의 프로젝트',
    heartsrc: '/img/emptyhart.jpg',
  },
];

export const defaultProject = {
  category: '게임',
  name: '언더테일(UnderTail)',
  end_date: '2022-12-31',
  target_amount: '560,000',
  counted_user_num: 24,
  price: '24,000',
  thumbnail_image: '/media/default-img.png',
  comment:
    "언더테일은 토비 폭스가 제작한 2015년 9월 15일에 출시된 인디\n게임이다. 한국어로 '지하 이야기' 정도로 번역할 수 있겠다. 2013년부터\n킥스타터를 통해 투자받은 금액으로 제작되었으며 릴리즈 영상 출시 이후\n백만 장 이상이 팔리며 상업적인 성공을 거두었다. 타임지나 IGF, IGN,\nSWSX 등의 시상식에서 상을 수상하며 평단으로부터 높은 평가를 받았다.\n스팀과 공식 홈페이지에서 살 수 있으며, 공식 홈페이지에서 구매하면\n스팀 키와 함께 DRM Free 버전을 받을 수 있다. 정가는\n9.99달러(10,500원)로, 사운드트랙 포함 버전 17.99달러(19,000원)이다.",
  intent:
    "언더테일은 토비 폭스가 제작한 2015년 9월 15일에 출시된 인디\n게임이다. 한국어로 '지하 이야기' 정도로 번역할 수 있겠다. 2013년부터\n킥스타터를 통해 투자받은 금액으로 제작되었으며 릴리즈 영상 출시 이후\n백만 장 이상이 팔리며 상업적인 성공을 거두었다. 타임지나 IGF, IGN,\nSWSX 등의 시상식에서 상을 수상하며 평단으로부터 높은 평가를 받았다.\n스팀과 공식 홈페이지에서 살 수 있으며, 공식 홈페이지에서 구매하면\n스팀 키와 함께 DRM Free 버전을 받을 수 있다. 정가는\n9.99달러(10,500원)로, 사운드트랙 포함 버전 17.99달러(19,000원)이다.",
  details:
    "언더테일은 토비 폭스가 제작한 2015년 9월 15일에 출시된 인디\n게임이다. 한국어로 '지하 이야기' 정도로 번역할 수 있겠다. 2013년부터\n킥스타터를 통해 투자받은 금액으로 제작되었으며 릴리즈 영상 출시 이후\n백만 장 이상이 팔리며 상업적인 성공을 거두었다. 타임지나 IGF, IGN,\nSWSX 등의 시상식에서 상을 수상하며 평단으로부터 높은 평가를 받았다.\n스팀과 공식 홈페이지에서 살 수 있으며, 공식 홈페이지에서 구매하면\n스팀 키와 함께 DRM Free 버전을 받을 수 있다. 정가는\n9.99달러(10,500원)로, 사운드트랙 포함 버전 17.99달러(19,000원)이다.",
};
